// =============================================================================
// firebase_options.dart — Firebase Configuration (Auto-Generated)
// Firebase 配置（自动生成）
//
// Auto-generated by FlutterFire CLI. Contains Firebase project configuration
// for all platforms: Android, iOS, macOS, Web, Windows.
// Project ID: aura-habit-tra
//
// 由 FlutterFire CLI 自动生成。包含所有平台的 Firebase 项目配置：
// Android、iOS、macOS、Web、Windows。
// 项目 ID：aura-habit-tra
// =============================================================================

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSEazJpAqF5yWvLTKVmT1v-vJ0g367qzo',
    appId: '1:314464093764:web:c2ebce98e0559ed2781e11',
    messagingSenderId: '314464093764',
    projectId: 'aura-habit-tra',
    authDomain: 'aura-habit-tra.firebaseapp.com',
    storageBucket: 'aura-habit-tra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYx5_KSv_VEyTgd9no-Jj0rrL9bCPfEA',
    appId: '1:314464093764:android:6ad655cd4e65ca98781e11',
    messagingSenderId: '314464093764',
    projectId: 'aura-habit-tra',
    storageBucket: 'aura-habit-tra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHMoiKh5KDNv9EkNRI8ZFWJ2NkVDlLvAI',
    appId: '1:314464093764:ios:4bb91343dadca47e781e11',
    messagingSenderId: '314464093764',
    projectId: 'aura-habit-tra',
    storageBucket: 'aura-habit-tra.firebasestorage.app',
    iosBundleId: 'com.aura.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHMoiKh5KDNv9EkNRI8ZFWJ2NkVDlLvAI',
    appId: '1:314464093764:ios:4bb91343dadca47e781e11',
    messagingSenderId: '314464093764',
    projectId: 'aura-habit-tra',
    storageBucket: 'aura-habit-tra.firebasestorage.app',
    iosBundleId: 'com.aura.habittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSEazJpAqF5yWvLTKVmT1v-vJ0g367qzo',
    appId: '1:314464093764:web:c28e4805063fc004781e11',
    messagingSenderId: '314464093764',
    projectId: 'aura-habit-tra',
    authDomain: 'aura-habit-tra.firebaseapp.com',
    storageBucket: 'aura-habit-tra.firebasestorage.app',
  );
}
